title: 桃花源
email: TakeActionBiz@hotmail.com
description: TakeAction_行动的部落格。这里会记录一些名言、Excel函数知识、英语学习分享。不断学习、进步，努力变得优秀。
baseurl: "/Blog" # the subpath of your site, e.g. /blog
#url: "https://pykm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://www.taxingdong.com"
twitter_username: jekyllrb
github_username:  PYkm

paginate: 5
paginate_path: "/page:num"


plugins: [jekyll-paginate]

markdown: kramdown #kramdown,rdiscount,redcarpet